---
title: "UCR_stationary_classification"
author: "Juan Carlos Bellassai"
output: pdf_document
---

```{r setup, include=FALSE}
# library(devtools)
# library(githubinstall)
#install_github("juancbellass/time-series-r-package", force = TRUE)
pkgs = c("ggplot2", "TSdist", "philentropy", "caret", "Metrics", "dtw",
         "parallel", "SimilarityMeasures", "TSSimilarityIndeces")
inst = lapply(pkgs, library, character.only = TRUE) # Load them
```

```{r}
common_path_test <- "C:/Users/Usuario/Google Drive (juancbellassai@mi.unc.edu.ar)/Juanc Doctorado/data_sets/UCR/UCR-estacionarias/test/"
common_path_train <- "C:/Users/Usuario/Google Drive (juancbellassai@mi.unc.edu.ar)/Juanc Doctorado/data_sets/UCR/UCR-estacionarias/train/"

primary_dirs <- list.files(common_path_test, pattern = "*.csv")

df.test.list <- list()
df.train.list <- list()
#nro.series = 30 # number of series per dataset

c <- 1 #counter
for (dir in primary_dirs) {
  df.test.list[[c]] <- read.csv(paste(common_path_test,dir, sep=""), header = TRUE)
  df.train.list[[c]] <- read.csv(paste(common_path_train,dir, sep=""), header = TRUE)
  c <- c+1
}

# Remove the string "-contaminados.csv" from each name in the list
primary_dirs <- gsub("-estacionarias.csv", "", primary_dirs)
names(df.test.list) <- primary_dirs
names(df.train.list) <- primary_dirs
df.names <- names(df.test.list); df.names
```

```{r}
Pearsons.Measure <- function(s1, s2){return(1-cor(s1, s2))}

index.list <- list(SSIMT = SSIMT,
                   Manhattan = ManhattanDistance, #1
                   Euclidean = EuclideanDistance, #2
                   Chebyshev = Chebyshev.Measure, #3
                   MSE = mse, #4
                   Frechet = Frechets.Measure, #5
                   DTW = DTW.Measure, #6
                   ERP = ERP.Measure, #7
                   EDR = EDR.Measure, #8
                   Fourier = FourierDistance, #9
                   Pearson = Pearsons.Measure, #10
                   CORT = CORT.Measure, #11
                   Chouakria = CortDistance, #12
                   LCSS = LCSS.Measure) #13

index.names <- names(index.list); index.names 
```

```{r}

```



